### ISSUE TITLE
no /api endpoint

### ISSUE THREAD

**Issue by gstorme** [mwvdev/aptpeeker#2]
Hi,

The docker container mwvdev/aptpeeker does not seem to provide an endpoint for /api when running?
The logs display `Exposing 2 endpoint(s) beneath base path '/actuator'`, but /api returns a 404.

Do I need to change something to enable this?

**Comment by mwvdev** [comment]
Hi,

I appreciate your reports! It seems I still have a few kinks to iron out in my documentation. I recently refactored so that the update endpoint also takes the server parameter as a path parameter, but I forgot to update the documentation. The endpoint should be `http://localhost:8080/api/package/updates/server-name-goes-here`.

The endpoint is shielded by `spring-security`. The password for the default spring security user, `user`, needs to be assigned by setting the `SPRING_SECURITY_USER_PASSWORD` environment variable.

I just tested it out a bit on my machine, and for this to work you will also need to add a bridge network to the docker run command. This is to allow AptPeeker to reach Slack.

I have updated the documentation in the README to reflect all of these things, please let me know if this works for you! I'm amazed at how much I've actually missed in the documentation :-)

**Comment by gstorme** [comment]
Great, thanks!
Yeah but writing docs isn't the most fun thing to do, I get it :)
